### PR TITLE
Videos have the wrong size when exporting them with a filter

### PR DESCRIPTION
**Pull request by adriana-elizondo**
After applying a filter to a video, when exporting it the dimensions were wrong.
This PR removes the size specification in the renderer used by the `VideoCompositor` so that the default is used.

To test it in Orangina:
-Open the editor to create a new post.
-Select a video from your phone or record a new one.
-Add a filter to your video and tap on the blue arrow to select it.
-The size of the video in the editor shouldn't look distorted or different.
-Post the video.
-The video should be posted with the selected filter and the correct dimensions.
-Bonus: try with videos in different orientations and with images and GIFs too, to make sure they weren't affected.

### CODE REVIEW

**Comment by bjtitus** [comment]
@adriana-elizondo What do you think about gating this change behind the `scaleMediaToFill` flag by changing the call sites in `Renderer` to pass a `nil` `size` to these methods? This way the Wordpress app wouldn't be affected.

[Renderer.swift:134](https://github.com/tumblr/kanvas-ios/blob/90f783b711ecacd1efa7e1dcd8c043e3a549c5ac/Classes/Rendering/Renderer.swift#L134)
```diff
---let (finalMediaTransform, outputDimensions) = configureScaleToFill(sampleBuffer: sampleBuffer, size: scaleToFillSize)
+++let (finalMediaTransform, outputDimensions) = configureScaleToFill(sampleBuffer: sampleBuffer, size: settings?.features.scaleMediaToFill == true ? scaleToFillSize : nil)
```

[Renderer.swift:207](https://github.com/tumblr/kanvas-ios/blob/90f783b711ecacd1efa7e1dcd8c043e3a549c5ac/Classes/Rendering/Renderer.swift#L207)
```diff
---let (finalMediaTransform, outputDimensions) = configureScaleToFill(sampleBuffer: sampleBuffer, size: scaleToFillSize)
+++let (finalMediaTransform, outputDimensions) = configureScaleToFill(sampleBuffer: sampleBuffer, size: settings?.features.scaleMediaToFill == true ? scaleToFillSize : nil)
```

[RendererPatch.patch.zip](https://github.com/tumblr/kanvas-ios/files/7787106/RendererPatch.patch.zip)

**Comment by adriana-elizondo** [comment]
> @adriana-elizondo What do you think about gating this change behind the `scaleMediaToFill` flag by changing the call sites in `Renderer` to pass a `nil` `size` to these methods? This way the Wordpress app wouldn't be affected.
> 
> [Renderer.swift:134](https://github.com/tumblr/kanvas-ios/blob/90f783b711ecacd1efa7e1dcd8c043e3a549c5ac/Classes/Rendering/Renderer.swift#L134)
> 
> ```diff
> ---let (finalMediaTransform, outputDimensions) = configureScaleToFill(sampleBuffer: sampleBuffer, size: scaleToFillSize)
> +++let (finalMediaTransform, outputDimensions) = configureScaleToFill(sampleBuffer: sampleBuffer, size: settings?.features.scaleMediaToFill == true ? scaleToFillSize : nil)
> ```
> 
> [Renderer.swift:207](https://github.com/tumblr/kanvas-ios/blob/90f783b711ecacd1efa7e1dcd8c043e3a549c5ac/Classes/Rendering/Renderer.swift#L207)
> 
> ```diff
> ---let (finalMediaTransform, outputDimensions) = configureScaleToFill(sampleBuffer: sampleBuffer, size: scaleToFillSize)
> +++let (finalMediaTransform, outputDimensions) = configureScaleToFill(sampleBuffer: sampleBuffer, size: settings?.features.scaleMediaToFill == true ? scaleToFillSize : nil)
> ```
> 
> [RendererPatch.patch.zip](https://github.com/tumblr/kanvas-ios/files/7787106/RendererPatch.patch.zip)

yes, you are totally right. Ill update it. Thanks Brandon!

**Review by bjtitus — APPROVED** [review]
:shipit: Looks good to me!

**Comment by bjtitus** [comment]
@adriana-elizondo Do you want to make a new version? I think you should be able to just increment the version number like in this commit and the release will be handled. https://github.com/tumblr/kanvas-ios/commit/0dc70d43ca039096b025c3c7fe0e311121238a85

**Pull request merged**
